# Generated by Django 5.1.7 on 2025-04-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
